# 股票监控配置文件

# 股票代码列表
stock_codes:
  - code: "SH.515050" #通讯ETF
  - code: "SH.562950" #消费电子ETF
  - code: "SZ.159995" #芯片ETF
  - code: "SH.588000" #科创50ETF
  - code: "SZ.300750" #宁德时代
  - code: "SH.603629" #利通电子

# 订阅类型
sub_types:
  - "QUOTE"
  - "RT_DATA"
  - "KL_1MIN"

# 刷新间隔（秒）
interval: 5

# 最大并发线程数
max_workers: 5

# 是否循环监控（true: 循环, false: 单次查询）
loop: true
